### ISSUE TITLE
What are the things need to run these models on my own data sets?

### ISSUE THREAD

**Issue by tiru1930** [david-yoon/Learning2rankQA_HRDE_LTC#1]
Hi 

My data set has document ,query with corresponding label (0/1 0 for negative  1 for positive). I want to  test your working models on my  own data set. What are the  steps need to fallow to create the data which i can feed to any one your model architectures

**Comment by david-yoon** [comment]
Hi, thank you for your interest.

The repository contains three types of code “src_samsungQA”, “src_ubuntu_v1” and “src_ubuntu_v2”. Those three types of code are very similar (actually almost same). Main differences lie in the data reading part.
So I’ll explain the way to use the code with your dataset assuming that you’re going to use the code in “src_ubuntu_v2” folder.

[overview]

For the preprocessing stage, please refer the code in the “QA_HRDE_LTC/preprocessing/”

First, generate dictionary according to your dataset for converting your “sequence of text” data into “sequence of index” data
In your dataset, put “__eot__” token to the place that can be considered a chunk. (i.e. new line)
Convert your dataset

[detail]

Preparing following pickle files from your dataset
1.  QA_HRDE_LTC/data/ubuntu_v2/v2_data.pkl
2.  QA_HRDE_LTC/data/ubuntu_v2/v2_data_test.pkl
3.  QA_HRDE_LTC/data/ubuntu_v2/v2_dic.pkl
4.  QA_HRDE_LTC/data/ubuntu_v2/v2_glove.pkl

Then you can train your dataset using the script 
    train → QA_HRDE_LTC/src_ubuntu_v2/run_HRDE.sh
    Inference → QA_HRDE_LTC/src_ubuntu_v2/http://eval_HRDE.py

[How to prepare the dataset]

1. v2_data.pkl : dataset for (train, valid, test)
    refer the code : preprocessing/Gendic_Convert2index.ipynb

v2_data.pkl ← [train, valid, test]
train[‘c’][number_of_sample]  ← context sentence    ( sequence of index )
train[‘r’][number_of_sample]  ← response sentence ( sequence of index )
train[‘y’][number_of_sample]  ← label (0 or 1)

‘valid’ and ‘test’ are same as ‘train’


2. v2_data_test.pkl : just shorten version of v2_data.pkl
    refer the code : preprocessing/Gendic_Convert2index.ipynb

train_set_test = {}
valid_set_test = {}
test_set_test = {}

train_set_test['c'] = train_set['c'][:500]
train_set_test['r'] = train_set['r'][:500]
train_set_test['y'] = train_set['y'][:500]

valid_set_test['c'] = valid_set['c'][:5000]
valid_set_test['r'] = valid_set['r'][:5000]
valid_set_test['y'] = valid_set['y'][:5000]

test_set_test['c'] = test_set['c'][:5000]
test_set_test['r'] = test_set['r'][:5000]
test_set_test['y'] = test_set['y'][:5000]

pickle.dump( [train_set_test, valid_set_test, test_set_test], open('../data/ubuntu_v2/v2_data_test.pkl', 'w') )

    
3. v2_dic.pkl: dictionary for the dataset
    refer the code : preprocessing/Gendic_Convert2index.ipynb
dic[‘token’] = index


4. v2_glove.pkl: pre-trained word embedding from Glove
    refer the code : preprocessing/apply_glove.ipynb

Numpy[ len(dictionary) ][ 300 ] : we use 300-d glove, “glove.840B.300d.txt”

Hope this will help you.

**Comment by david-yoon** [comment]
In your case, 

document --> context ( 'c' )
query --> response ( 'r' )
label --> label ( 'y' )

chuck == sentence (or passage) in document
